import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { Roboto } from "next/font/google";
import Header from "./components/Header";
import ToastifyContainer from "./components/ToastifyContainer";
import StoreProvider from "@/redux/StoreProvider";
import { useAuth } from "@/hooks/auth";
import TopicList from "./components/TopicList";
import store from "@/redux/store";
import { fetchTopicData, fetchTopics } from "@/redux/Topic/TopicSlice";

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Mern Sozluk",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  await store.dispatch(fetchTopics());

  const { topicList, topicListStatus } = store.getState().topic;

  const { loginStatus, user } = await useAuth.fromServer();

  return (
    <html lang="en">
      <body className={`${roboto.className} bg-dark text-white`}>
        <StoreProvider
          preloadedState={{
            user: {
              loginned: loginStatus,
              loggedUser: user,
            },
            topic: {
              topicList,
              topicListStatus,
            },
          }}
        >
          <Header />
          <ToastifyContainer />
          <div className="grid grid-cols-5">
            <div className="col-span-1 hidden md:block">
              <TopicList />
            </div>
            <div className="col-span-5 md:col-span-4 relative">{children}</div>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
