import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { Roboto } from "next/font/google";
import Header from "./components/Header";
import ToastifyContainer from "./components/ToastifyContainer";
import StoreProvider from "@/redux/StoreProvider";
import { useAuth } from "@/hooks/auth";
import TopicList from "./components/TopicList";

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Mern Sozluk",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {

  const { loginStatus, user } = await useAuth.fromServer();

  return (
    <html lang="en">
      <body className={`${roboto.className} bg-dark text-white container`}>
        <StoreProvider
          preloadedState={{
            user: {
              loginned: loginStatus,
              loggedUser: user,
            },
          }}
        >
          <Header />
          <ToastifyContainer />
          <div className="flex flex-col-reverse lg:grid lg:grid-cols-5">
            <div className="lg:col-span-1">
              <TopicList />
            </div>
            <div className="lg:col-span-4 relative">{children}</div>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
